// src/models/InsurancePartner.js
import mongoose from "mongoose";

/**
 * InsurancePartner
 * - Used when customer selects "Insurance" as payment option
 * - Each partner has:
 *    - name + code
 *    - allowed countries
 *    - status (active/inactive)
 *    - billing rules (monthly invoice)
 *    - contact info
 */
const InsurancePartnerSchema = new mongoose.Schema(
  {
    // Unique short code used internally (e.g. "OUTSURANCE", "AAKENYA")
    code: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      unique: true,
      index: true,
    },

    // Display name shown in app dropdown
    name: {
      type: String,
      required: true,
      trim: true,
    },

    // Optional brand logo
    logoUrl: {
      type: String,
      default: "",
      trim: true,
    },

    // Which countries this insurance is available in (multi-country routing)
    countryCodes: {
      type: [String],
      default: ["ZA"],
      set: (arr) =>
        Array.isArray(arr)
          ? arr.map((x) => String(x).trim().toUpperCase()).filter(Boolean)
          : ["ZA"],
      index: true,
    },

    // If disabled, app should not show it
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },

    /**
     * Billing model:
     * - insurance jobs are NOT paid immediately by customer
     * - partner is invoiced monthly based on usage
     */
    billing: {
      billingType: {
        type: String,
        enum: ["MONTHLY_INVOICE"],
        default: "MONTHLY_INVOICE",
      },

      // Optional contract terms
      contractStartDate: { type: Date, default: null },
      contractEndDate: { type: Date, default: null },

      // If you want per-partner markup/discount later
      rateMultiplier: {
        type: Number,
        default: 1,
        min: 0,
      },

      // VAT/tax rules (country-specific handling later)
      vatNumber: { type: String, default: "", trim: true },
      taxPercentage: { type: Number, default: 0, min: 0, max: 100 },
    },

    /**
     * Contact info for invoicing / support
     */
    contact: {
      email: { type: String, default: "", trim: true, lowercase: true },
      phone: { type: String, default: "", trim: true },
      contactPerson: { type: String, default: "", trim: true },
    },

    /**
     * Partner settings
     */
    settings: {
      // If true: only codes generated by TowMech system can be used
      requireCode: { type: Boolean, default: true },

      // If true: code must match selected insurance partner
      strictPartnerMatch: { type: Boolean, default: true },

      // How long codes remain valid
      codeValidityDays: { type: Number, default: 30, min: 1, max: 3650 },

      // Rate limiting per code (optional)
      maxJobsPerCode: { type: Number, default: 1, min: 1 },
    },

    /**
     * Audit fields
     */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  { timestamps: true }
);

// Safety: keep uniqueness clean
InsurancePartnerSchema.pre("save", function (next) {
  if (this.code) this.code = String(this.code).trim().toUpperCase();
  if (this.name) this.name = String(this.name).trim();
  next();
});

const InsurancePartner =
  mongoose.models.InsurancePartner ||
  mongoose.model("InsurancePartner", InsurancePartnerSchema);

export default InsurancePartner;